name: tenderly-frontend
region: sfo
static_sites:
  - name: web
    github:
      repo: zubair480/tenderly
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm ci && npm run build
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: VITE_USE_MOCK
        value: "false"
        scope: BUILD_TIME
        type: GENERAL
      - key: VITE_API_URL
        value: "https://hammerhead-app-gwq3o.ondigitalocean.app"
        scope: BUILD_TIME
        type: GENERAL
