name: tenderly-frontend
static_sites:
  - name: web
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: VITE_USE_MOCK
        value: "true"
        scope: BUILD_TIME
        type: GENERAL
